### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by PabloSzx** [ecyrbe/gwent-pro-ladder-lib#1]
Hi, I'm testing it and doesn't work properly 

This is the code
<img width="371" alt="screen shot 2017-10-06 at 3 20 31 am" src="https://user-images.githubusercontent.com/8672915/31265547-bd30c654-aa45-11e7-925e-744c8f287b01.png">

This is the log
<img width="95" alt="screen shot 2017-10-06 at 3 24 01 am" src="https://user-images.githubusercontent.com/8672915/31265554-cd5d051a-aa45-11e7-9420-899915b15225.png">

**Comment by ecyrbe** [comment]
This should be fixed now.
